// DOM Elements
const spiceScreen = document.getElementById("spice-screen");
const homeScreen = document.getElementById("home-screen");
const gameScreen = document.getElementById("game-screen");

const selectPlayersBtn = document.querySelector("#spice-screen .action-btn");
const playBtn = document.querySelector(".play-btn");
const nextBtn = document.querySelector("#game-screen .action-btn");

const challengeTitle = document.querySelector(".challenge-card h3");
const challengeText = document.querySelector(".challenge-card p");
const playerName = document.querySelector("#game-screen h2");

// Sample Data
const players = ["", "", "", ""];

const truths = [
  "What's your biggest fear?",
  "What's a secret you've never told anyone?",
  "Who was your first crush?",
  "Have you ever lied to your best friend?",
  "Have you ever accidentally sent a sext to the wrong person?",
  "Who would you like to sext right now?",
  "...Why don’t you do it?",
  "Who in your contact list would you most want us to have a threesome with?",
  "What’s your favorite body part of mine?",
  "What’s your biggest roleplay fantasy?",
  "Who was the first person you had a crush on?",
  "Where’s the craziest place you want to hook up with me?",
  "Have you ever had a sex dream about me?",
  "What’s the weirdest thing anyone has ever said to you during sex?",
  "What’s the weirdest thing you’ve ever said to anyone during sex?",
  "Would you like to make a sex tape with me?",
  "Would you rather do a pole dance or a striptease?",
  "What part of my body would you like to lick right now?",
  "How many one-night stands have you had?",
  "Have you ever put a sexy selfie on social media?",
  "What’s your biggest turn-on when you think about me?",
  "If I gave you whipped cream right now, what would you do with it?",
  "What’s the dirtiest thing you’d like me to do to you?",
  "Do you think my best friend is hot?",
  "How soon after meeting someone have you slept with them for the first time?",
  "Have you ever broken a bed during sex?",
  "Would you rather only sext for the rest of your life, or only have phone sex?",
  "What common turn-off really turns you on?",
  "When did you first realize you were attracted to me?",
  "Have you ever faked an orgasm?",
  "Have you ever faked an orgasm... with me?",
  "Have you ever slept with a co-worker?",
  "Would you want a threesome with me and my best friend?",
  "Would you want a threesome with me and your best friend?",
  "What’s the craziest thing you’ve done in a sex dream?",
  "Have you ever been turned on at work?",
  "...What happened?",
  "...And what did you do about it?",
  "Have you ever been to a sex club?",
  "...Would you like to?",
  "When was the last time I turned you on?",
  "Is there a sex toy you’d like to try on me?",
  "Have you ever injured yourself during sex?",
  "Have you ever had sex in a public place?",
  "When was the last time you touched yourself?",
  "...What were you thinking about?",
  "Would you rather be dominant or submissive?",
  "Have you ever fallen asleep during sex?",
  "Have you ever been to a strip club?",
  "Has anyone ever walked in on you during sex?",
  "Would you rather only use your tongue or only use your fingers?",
  "What’s your favorite thing about my body?",
  "Would you rather only have morning sex for the rest of your life, or never have morning sex again?",
  "What was your first sexual fantasy?",
  "Have you ever tried swinging or partner swapping?",
  "...Would you like to?",
  "Which celebrity would you like to see me make out with?",
  "Would you like to watch me make out with my best friend?",
  "Would you like to watch me make out with your best friend?",
  "How would you describe my sexual personality?",
  "What’s your favorite memory of us having sex?",
  "...Is there anything that could have made it even better?",
  "What’s the sexiest gift I could give you?",
  "What’s the sexiest gift you’d like to give me?",
  "Have you ever kept a relationship secret?",
  "What’s your most romantic memory of me?",
  "Have you ever experimented with people of different genders?",
  "Do you know your love language? If so, what is it?",
  "Do you know your desire style?",
  "What's one thing you struggle with in relationships?",
  "What's the best thing you think you bring to relationships?",
  "What first made you attracted to me?",
  "What usually turns you on?",
  "Do you know what usually turns me on?",
  "What's a seemingly nonsexual thing that turns you on?",
  "Have you ever had sex with more than one person in a day?",
  "What's the biggest age difference you've ever had with a partner?",
  "What's the most embarrassing thing that’s happened to you during sex?",
  "Have you ever cheated? (Bonus question for the brave: Did it turn you on?)",
  "Have you ever turned down a sexual opportunity and regretted it?",
  "Have you ever hooked up with someone you regret?",
  "When did you learn what sex was? What’s the story?",
  "Have you ever faked an orgasm?",
  "Have you ever admitted to faking an orgasm?",
  "Has anyone ever admitted to faking an orgasm with you?",
  "Have you ever accidentally sent a sext to the wrong person?",
  "How do you feel about shower sex? Love it, hate it, or super neutral?",
  "What about pool/beach sex?",
  "What's the sexiest songyou've ever heard? What about it turns you on?",
  "What's the sexiest movie or TV scene you've ever watched?",
  "When are you the most horny?",
  "Do you remember your sexual awakening? Tell me about it.",
  "What's the most amount of times you've orgasmed in a day?",
  "What's the most amount of times you've orgasmed in an hour?",
  "If we opened up our relationship, who would be the first person you’d want to have sex with?",
  "Who would be in your dream orgy?",
  "Who would you invite if you were hosting a sex party? Celebrities and famous people included.",
  "What do you remember most about the first time you ever had sex?",
  "Who was the first person you ever had sex with?",
  "Who is the weirdest person you’ve had a sex dream about?",
  "Have you ever had a sex dream about me?",
  "If you could have sex with one person from your past again, who would it be?",
  "Would you ever want to watch me have sex with someone else?",
  "What do you think about sex toys?",
  "If you're open to them, what’s one sex toy you want me to try on you?",
  "If you're familiar with sex toys, what type is your favorite?",
  "What’s a fantasy you’ve never told me about?",
  "What memory from our sex life turns you on the most?",
  "What would be your dream role-play scenario?",
  "Have you ever gotten turned on at work (or while WFH)? What did you do about it?",
  "Have you ever hooked up with a stranger or had a one-night stand?",
  "Have any you ever hooked up with an ex?",
  "Do you prefer using your tongue or fingers on me? Which do you like me to use on you?",
  "How do you feel about swinging or partner swapping? Does the idea turn you on?",
  "What's something I do that isn't sexual but turns you on?",
  "Would you ever want to go to a sex club or sex party with me?",
  "Where is the most random place you’ve ever masturbated?",
  "How do you feel about mutual masturbation?",
  "Have you ever had sex on a plane?",
  "What’s #1 on your sexual bucket list right now?",
  "Have you ever been caught having sex?",
  "Have you ever accidentally walked in on anyone getting it on?",
  "Have you ever had sex in public?",
  "Do you ever watch porn? Tell me what type you usually gravitate toward.",
  "What’s the kinkiest thought you’ve ever had about me?",
  "What’s a sex act most people like that you think is overrated?",
  "What sexual activity (or activities) do you think is underrated?",
  "Have you ever fantasized about a teacher or authority figure? Who was it and why?",
  "Do you know the last name of everyone you’ve had sex with? What about first?",
  "Kiss on the first date: Yay or nay?",
  "Sex on the first date: Yay or nay?",
  "What is your favorite body part for me to suck on?",
  "What's your favorite body part to be kissed?",
  "Would you prefer to dominate me in bed or do you want me to dominate you in bed?",
  "Do you like being nibbled on or lightly bitten? Where?",
  "How do you feel about nipple play?",
  "How do you feel about butt stuff?",
  "What's your favorite sex toy to use on me?",
  "What's your favorite sex toy to use together?",
  "What's the kinkiest thing you've ever done?",
  "What's the kinkiest thing you'd like to do?",
  "What’s the hottest sex dream you’ve ever had?",
  "Tell me one thing I could do that would make you immediately orgasm.",
  "Which is your favorite kind of sex: soft, slow, and sweet or aggressive, fast, and feisty?",
  "If I gave you a free pass to hook up with one celebrity, who would it be and why?",
  "What item of clothing do you think I look sexiest in?",
  "Describe my in-bed personality in three words.",
  "If I were handcuffed to the bed, what would you do to me?",
  "Would you ever want to be blindfolded?"
];

const dares = [
  "Show everyone your most embarrassing photo.",
  "Do 10 push-ups right now.",
  "Sing a song loudly.",
  "Act like a cat for 1 minute.",
  "Kiss your partner passionately for 30 seconds.",
  "Whisper your dirtiest fantasy to your partner.",
  "Remove one piece of clothing.",
  "Give your partner a sensual massage for 1 minute.",
  "Let your partner write a naughty word on your body with their finger.",
  "Do a seductive dance for your partner.",
  "Share your most embarrassing sexual experience.",
  "Lick whipped cream off your partner's body.",
  "Blindfold your partner and feed them something sweet or spicy.",
  "Send a flirty text to your partner right now.",
  "Imitate your partner's sexiest move.",
  "Tell your partner what you want to do to them tonight.",
  "Let your partner tie your hands and tease you for 1 minute.",
  "Give your partner a lap dance.",
  "Kiss your partner's neck slowly for 20 seconds.",
  "Describe your favorite position in detail.",
  "Take a sexy selfie and show it to your partner.",
  "Put an ice cube in your underwear for one minute.",
  "Perform a sexy belly dance for your partner.",
  "Blindfold your partner and guide them around your body using only touch.",
  "Undress your partner using only your teeth.",
  "Clean the house naked.",
  "Go about your normal day but with no underwear on.",
  "Give your partner a massage, blindfolded.",
  "Remove your partner’s underwear using only your feet.",
  "Use each other as a human plate — whipped cream, chocolate sauce, whatever takes your fancy!",
  "Share a fantasy that your loved one’s never heard before.",
  "Handcuff your partner and treat them to their favorite turn-ons.",
  "Read an erotic bedtime story out loud.",
  "Set up a nude photo shoot and capture your favorite poses.",
  "Go skinny dipping in your local river or lake.",
  "Sext your partner during work.",
  "Touch yourselves while your partner watches.",
  "Give your partner a lap dance.",
  "Pick one part of your body and have your partner focus all their attention there.",
  "Choose a place you’ve never had sex and take your partner there.",
  "Draw a picture with whipped cream on your partner’s body.",
  "...Then lick it off.",
  "Try a new pick-up line on your partner.",
  "Re-enact an X-rated version of your first kiss.",
  "Choose your fantasy orgy guests from your partner’s contact list.",
  "Play the rest of the game naked.",
  "Feed your partner using only your mouth.",
  "Give your significant other a full-body massage.",
  "Act out the first time you slept together.",
  "Have sex in a new part of the house for the first time.",
  "Kiss your partner passionately, like the climax of a movie.",
  "Perform a sexy pole dance with a broom or a mop.",
  "Use body paint to turn each other into a work of art.",
  "Twerk to the sexiest song you can think of.",
  "Confess your kinky guilty pleasure and try it together.",
  "Let your partner dress you up, then direct you in a striptease.",
  "Challenge your loved one to a sexy pillow fight.",
  "Spell out what you want to do to your partner using only emojis.",
  "Pretend you work at a phone sex line and have your partner call in.",
  "Blindfold yourself and guess which part of your partner’s body you’re touching.",
  "Play with melted wax (but be careful!)",
  "Hide chocolate or candy in your clothes and have your significant other find it.",
  "Send a sexy selfie when they least expect it.",
  "Balance an ice cube on your belly button for as long as you can bear it.",
  "Show your partner the last X-rated clip you watched.",
  "...And describe why it turned you on.",
  "Put on your significant other’s underwear and strut your stuff on the catwalk.",
  "Shave your partner’s body hair.",
  "Pretend to give oral sex to the nearest object you see.",
  "Try tantric sex.",
  "Leave a steamy voicemail for an ex or another friend.",
  "Lick peanut butter, whipped cream, or chocolate sauce off someone else’s finger.",
  "Fake an orgasm for one minute.",
  "Play spin the bottle and kiss the person the bottle chooses.",
  "Act out your favorite sex position with the person to your left.",
  "Pretend to give oral sex to a bottle for 30 seconds.",
  "If there’s a pool or a hot tub, go skinny-dipping.",
  "Hold hands with the person you know least in the group for one minute.",
  "Send a sexy selfie to someone in your contact list.",
  "Take a body shot. Balance the glass in your cleavage, on your torso — get creative!",
  "At the beach or a pool party? Draw a steamy image in sunscreen on a friend.",
  "Swap underwear with the person to your right.",
  "Reply to a social media post or story with a sexy emoji.",
  "Perform a pole dance on a nearby streetlight, or anything else that works!",
  "Transfer an ice cube from your mouth to someone else’s.",
  "Give a lap dance to a friend of your choice.",
  "Remove an item of clothing (or take a shot!)",
  "Snap a photo of a mystery part of your body and have the others guess.",
  "Wherever you are, twerk for 30 seconds.",
  "Hand over your dating apps to the group for two minutes.",
  "Perform a striptease for 30 seconds (if in private!)",
  "Roleplay a fantasy of your choice with another member of the group.",
  "Give a foot massage to the person on your right for one minute.",
  "Agree on a budget (we recommend around R20!) and let the person to your left order something steamy on your Amazon account.",
  "Send a sext to someone in your contact list."
];

// Functions
function showScreen(screen) {
  [spiceScreen, homeScreen, gameScreen].forEach(s => s.style.display = "none");
  screen.style.display = "flex";
}

function randomChallenge() {
  const isDare = Math.random() > 0.5;
  const player = players[Math.floor(Math.random() * players.length)];

  playerName.textContent = player;
  challengeTitle.textContent = isDare ? "Dare" : "Truth";
  challengeText.textContent = isDare
    ? dares[Math.floor(Math.random() * dares.length)]
    : truths[Math.floor(Math.random() * truths.length)];
}

// Event Listeners
selectPlayersBtn.addEventListener("click", () => {
  showScreen(homeScreen);
});

playBtn.addEventListener("click", () => {
  showScreen(gameScreen);
  randomChallenge();
});

nextBtn.addEventListener("click", () => {
  randomChallenge();
});
